nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com"
